% compile ucm_mean_pb
mex toolboxes/BSR/ucm/ucm_mean_pb.cpp -outdir toolboxes/BSR/lib;
    
% compile mex_contour_sides
mex toolboxes/BSR/gpb_src/matlab/segmentation/mex_contour_sides.cpp ...
    -outdir toolboxes/BSR/lib ...
    -Itoolboxes/BSR/gpb_src/include ...
       toolboxes/BSR/gpb_src/src/concurrent/threads/child_thread.cc ...
       toolboxes/BSR/gpb_src/src/concurrent/threads/runnable.cc ...
       toolboxes/BSR/gpb_src/src/concurrent/threads/thread.cc ...
       toolboxes/BSR/gpb_src/src/concurrent/threads/synchronization/synchronizables/synchronizable.cc ...
       toolboxes/BSR/gpb_src/src/concurrent/threads/synchronization/synchronizables/unsynchronized.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/ex_bad_cast.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/ex_not_found.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/ex_not_implemented.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/ex_index_out_of_bounds.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/ex_invalid_argument.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/ex_null_pointer_dereference.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/exception.cc ...
       toolboxes/BSR/gpb_src/src/lang/exceptions/throwable.cc ...
       toolboxes/BSR/gpb_src/src/lang/array.cc ...
       toolboxes/BSR/gpb_src/src/math/random/generators/rand_gen_uniform.cc ...
       toolboxes/BSR/gpb_src/src/math/random/sources/rand_source_default.cc ...
       toolboxes/BSR/gpb_src/src/math/random/sources/rand_source.cc ...
       toolboxes/BSR/gpb_src/src/math/random/sources/mersenne_twister_64.cc ...
       toolboxes/BSR/gpb_src/src/math/random/sources/rand_source_64.cc ...
       toolboxes/BSR/gpb_src/src/math/random/sources/system_entropy.cc ...
       toolboxes/BSR/gpb_src/src/math/random/util/randperm.cc ...
       toolboxes/BSR/gpb_src/src/math/matrices/matrix.cc ...
       toolboxes/BSR/gpb_src/src/math/matrices/exceptions/ex_matrix_dimension_mismatch.cc ...
       toolboxes/BSR/gpb_src/src/math/libraries/lib_image.cc ...
       toolboxes/BSR/gpb_src/src/math/libraries/lib_signal.cc ...
       toolboxes/BSR/gpb_src/src/math/math.cc ...
       toolboxes/BSR/gpb_src/src/math/exact.cc ...
       toolboxes/BSR/gpb_src/src/math/geometry/point_2D.cc ...
       toolboxes/BSR/gpb_src/src/math/geometry/seg_intersect.cc ...
       toolboxes/BSR/gpb_src/src/math/geometry/triangulation.cc ...
       toolboxes/BSR/gpb_src/src/math/geometry/triangle_2D.cc ...
       toolboxes/BSR/gpb_src/src/mlearning/clustering/clusterers/abstract/clusterer.cc ...
       toolboxes/BSR/gpb_src/src/mlearning/clustering/clusterers/abstract/weighted_clusterer.cc ...
       toolboxes/BSR/gpb_src/src/mlearning/clustering/clusterers/kmeans/basic_clusterer.cc;